config/routes.rb
Rails.application.routes.draw do

	 root  "batches#index"


	  get 'homes/home', to: 'homes#home'
	  get 'contacts/contact', to: 'contacts#contact'
	  get 'about_us', to: 'about_us#about_us'



  devise_for :admins

	resources :faculties
	resources :batches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
	belongs_to :faculty
end

app/models/faculty.rb
class Faculty < ApplicationRecord
	has_many :batches
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
	def about_us
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_admin!

end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
	def index
		@batches = Batch.all
	end

	def new
      @batch = Batch.new	
	end

	def create
		
	  @batch = Batch.new(batch_params)
	 
	 if @batch.save
	  redirect_to @batch
	else
		render 'new'
	end
    end 

	def show
		@batch = Batch.find(params[:id])
		
	end

	def edit
		@batch = Batch.find(params[:id])

	end

	def update
	 @batch = Batch.find(params[:id])

	 if @batch.update(batch_params)
      redirect_to @batch
    else
      render 'edit'
    end

	end


	def destroy
	 @batch = Batch.find(params[:id])
		 @batch.destroy
		redirect_to @batch
	end
	 
	private
	  def batch_params
	    params.require(:batch).permit(:batch_name, :start_at, :end_at, :faculty_id)
	  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def contact
		
	end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
	def index
		@faculties = Faculty.all
	end

	def new
      @faculty = Faculty.new	
	end

	def create
		  @faculty = Faculty.new(faculty_params)
		 
		 if @faculty.save
		  redirect_to @faculty
		else
			render 'new'
		end
    end 

	def show
		@faculty = Faculty.find(params[:id])
		
	end

	def edit
		@faculty = Faculty.find(params[:id])

	end

	def update
	 @faculty = Faculty.find(params[:id])

	 if @faculty.update(faculty_params)
      redirect_to @faculty
    else
      render 'edit'
    end

	end


	def destroy
	 @faculty = Faculty.find(params[:id])
		 @faculty.destroy
		redirect_to @faculty
	end
	 
	private
	  def faculty_params
	    params.require(:faculty).permit(:faculty_name, :contact, :email)
	  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def home
		
	end
end

app/controllers/private_policy_controller.rb
class PrivatePolicyController < ApplicationController
	def private_policy
		
	end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/private_policy_helper.rb
module PrivatePolicyHelper
end

app/views/about_us/about_us.html.erb
<h1>About Us</h1>
<p>Years of Experience and Expertise allows us to prepare the perfect study material for you. Subject-wise exhaustive course material covering complete examination syllabus with time saving tips and tricks, make our Correspondence & Publication Courses a must have for Government job aspirants. 🙂</p>

app/views/batches/_form.html.erb
<%= form_for @batch do |f| %>  

  <%= f.collection_select :faculty_id, Faculty.order(:faculty_name),:id,:faculty_name, include_blank: true %>

  <p>
    <%= f.label :Batch_name %><br>
    <%= f.text_field :batch_name %>
  </p>

  <p>
    <%= f.label :Batch_start_timing %><br>
    <%= f.time_select :start_at %>
  </p>
 
 <p>
    <%= f.label :Batch_end_timing %><br>
    <%= f.time_select :end_at %>
  </p>
 
 
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

    <%= link_to 'batches back', batches_path %> |

app/views/batches/edit.html.erb
<h1>edit Batch</h1>
<%= render 'form' %>

app/views/batches/index.html.erb
<h1>Listing batches</h1>
 <%= link_to 'New batch', new_batch_path %>
<table>
  <tr>
    <th>batch name</th>
        <th colspan="3"></th>

  </tr>
 
  <% @batches.each do |batch| %>
    <tr>
      <td><%= batch.batch_name %></td>
      <td><%= link_to 'Show', batch_path(batch) %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
      <td><%= link_to 'Destroy', batch_path(batch),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/batches/new.html.erb
<h1>New Batch</h1>
<%= render 'form' %>

app/views/batches/show.html.erb
<p>
	<strong>Faculty name</strong>
	<%= @batch.faculty.faculty_name %>
</p> 


<p>
	<strong>Batch name</strong>
	<%= @batch.batch_name %>
</p> 

<p>
	<strong>batch end timing</strong>
	<%= @batch.start_at.strftime("%H:%M") %>
</p>

<p>
	<strong>batch start timing</strong>
	<%= @batch.end_at.strftime("%H:%M") %>
</p>



<%= link_to 'Edit', edit_batch_path(@batch) %> |

<%= link_to 'Back', batches_path %>

app/views/contacts/contact.html.erb
<h1>Contact Us</h1>

<p>Contact No. :  12345678</p>
<p>Email id : coachingcentergmail.com</p>

app/views/faculties/_form.html.erb
<%= form_for @faculty do |f| %>  


  <p>
    <%= f.label :Faculty_name %><br>
    <%= f.text_field :faculty_name %>
  </p>

  <p>
    <%= f.label :Contact %><br>
    <%= f.text_field :contact %>
  </p>
 
 <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </p>
 
 
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

    <%= link_to 'faculties back', faculties_path %> |

app/views/faculties/edit.html.erb
<h1>Edit Faculty</h1>
<%= render 'form' %>

app/views/faculties/index.html.erb
<h1>Listing faculties</h1>
 <%= link_to 'New faculty', new_faculty_path %>
<table>
  <tr>
    <th>faculty name</th>
        <th colspan="3"></th>

  </tr>
 
  <% @faculties.each do |faculty| %>
    <tr>
      <td><%= faculty.faculty_name %></td>
      <td><%= link_to 'Show', faculty_path(faculty) %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
      <td><%= link_to 'Destroy', faculty_path(faculty),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>
<%= render 'form' %>

app/views/faculties/show.html.erb
<p>
	<strong>Faculty_name</strong>
	<%= @faculty.faculty_name %>
</p> 

<p>
	<strong>Contact</strong>
	<%= @faculty.contact %>
</p>

<p>
	<strong>Email</strong>
	<%= @faculty.email %>
</p>



<%= link_to 'Edit', edit_faculty_path(@faculty) %> |

<%= link_to 'Back', faculties_path %>

app/views/homes/home.html.erb
<h1>Home Page</h1>

<p>1 Web Designing. Web designing is a great opportunity for those who want to work independently. ...
2 VFX and Animation. ...
3 Hardware and Networking courses. ...
4 Software and Programming Language courses. ...
5 Tally. ...
6 Cyber security courses. ...
7 Microsoft Office and Typing courses. ...
</p>

<h1>AboutUs</h1>

<p>Years of Experience and Expertise allows us to prepare the perfect study material for you. Subject-wise exhaustive course material covering complete examination syllabus with time saving tips and tricks, make our Correspondence & Publication Courses a must have for Government job aspirants. 🙂</p>

<h1>Contact Us</h1>

<p>Contact No. :  12345678</p>
<p>Email id : coachingcentergmail.com</p>

app/views/layouts/_header.html.erb
     <header>

    <p class="navbar-text float-right" >

    <h1 style="text-align: left; color: lightcyan" >Ambitious Coaching</h1>

    <%= link_to "Home",homes_home_path, :class => 'navbar-link pooja' %>  &nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to "Contact Us",contacts_contact_path, :class => 'navbar-link pooja' %>  &nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to "About US",about_us_path, :class => 'navbar-link pooja'%> &nbsp;&nbsp;&nbsp;&nbsp;



    <% if admin_signed_in? %>
     
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link pooja' %> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link pooja'  %>



    <% else %>
      <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link pooja'  %> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "Login", new_admin_session_path, :class => 'navbar-link pooja'  %>
    <% end %>

     </header>
  
<style>
  .pooja{text-decoration: none;
  color: lightcyan;

}


</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



  <head>
    <title>Institute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

         <style>
           
           header
        {background-color: midnightblue;
        padding: 02px;
        text-align: right;
        font-size: 18px;
        }


        body{color: black;
          background-color: lightcyan}

    

         </style>
        
   
  <body>



      
   <%= render 'layouts/header' %>

       <p class="notice"><%= notice %></p>
       <p class="alert" style="color: red;"><%= alert %></p>


    <%= yield %>


  </body>
</html>

app/views/private_policy/private_policy.html.erb
<h1>Private Policy</h1>
<p> Online Privacy Policy Generator and Terms & Conditions Generator! Here at Free Privacy Policy, we've helped 815,960 website owners create easy-to-read, highly effective, custom privacy policies and terms & conditions agreements.

Our intuitive, easy-to-use system allows you to create a custom privacy policy or a terms & conditions agreement using our free website privacy policy generator or our free website terms & conditions generator.

All you do is answer a few simple questions about your business and your website privacy policy or website terms & conditions agreement is created and ready to add to your site. In fact, for most people it takes less than 15 minutes.

Our Privacy Policy Generator includes several compliance verification tools to help you effectively protect your customers privacy, while limiting your liability, all while adhering to the most notable state and federal privacy laws and 3rd party initiatives, including:</p>